// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionRunner
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SolutionRunnerString = "f4ad53e6-1564-48ba-8edf-d0950c6a713a";
        public static Guid SolutionRunner = new Guid(SolutionRunnerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowSolutionRunnerWindowCommand = 0x0100;
    }
}